# Generated by Django 3.1.4 on 2021-01-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conacts',
            name='email',
            field=models.EmailField(default='', editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='conacts',
            name='phone',
            field=models.CharField(default='', editable=False, max_length=13),
        ),
        migrations.AlterField(
            model_name='conacts',
            name='name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
