# Generated by Django 3.1.4 on 2021-01-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapi', '0002_auto_20210122_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conacts',
            new_name='Contacts',
        ),
    ]
