# Generated by Django 3.1.4 on 2021-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapi', '0003_auto_20210122_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
