# Generated by Django 3.1.4 on 2021-01-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapi', '0004_auto_20210122_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
