# Generated by Django 3.1.4 on 2021-01-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapi', '0005_auto_20210123_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
